print("Mafe R. Postrado")
print("Marlangga, Torijos Marinduque")
print("February 2,2002")
print("Marindue State College")
print("Batchelor of Science in Information Technology")
print("Second Year")
print("E")
print("Watching movies")
print("Eating")
print("Playing online games")
print("Surfing in internet")
print("Reading Wattpad Series")